Dev/light dependency
modelscope/data-juicer pull request #414
Opened 2024-09-03 10:57 UTC by BeachWang

1. Install OP dependency when they are executed: lazy import + check and install dependency before init function.
2. Clean cuda for each test in unit tests.

2024-09-05 09:32 UTC, drcege commented
既然手动将所有 `AvailabilityChecking` 更改为 `LazyLoader`了，为什么不将  import 批量改为 local import 呢？

在 `compute_stats` 和 `map` 内部使用时导入第三方库就能实现 lazy import 的效果，对引入 LazyLoader 感到困惑 🤔️

2024-09-05 12:40 UTC, BeachWang commented
> 既然手动将所有 `AvailabilityChecking` 更改为 `LazyLoader`了，为什么不将 import 批量改为 local import 呢？
> 
> 在 `compute_stats` 和 `process` 内部使用时导入第三方库看起来就能实现 lazy import 的效果，对引入 LazyLoader 感到困惑 🤔️

好像也可以。但是可能会出现多处地方需要import的情况，而且doc里面的样例也不是很好说明。

2024-09-05 12:49 UTC, drcege commented on data_juicer/utils/model_utils.py
> +            MODEL_ZOO[model_key].to('cpu')
这里有必要 `to.('cpu')` 吗，移动到 CPU 后与原来 GPU 上是两份不同的参数，不是原地修改

2024-09-05 12:49 UTC, drcege commented on data_juicer/utils/lazy_loader.py
> +    def __init__(self, local_name, parent_module_globals, name):
`local_name` 与 `name` 始终保持一致，可以只保留一个，简化接口

2024-09-05 12:49 UTC, drcege commented on data_juicer/utils/lazy_loader.py
> +    def __init__(self, local_name, parent_module_globals, name):
`parent_module_globals` 总是当前模块的 `globals()`，如果可以自动获取的话，也可以简化接口

2024-09-05 13:04 UTC, BeachWang commented on data_juicer/utils/model_utils.py
> +            MODEL_ZOO[model_key].to('cpu')
不是吧，没有to('cpu')会爆显存

2024-09-05 13:04 UTC, BeachWang commented on data_juicer/utils/lazy_loader.py
> +    def __init__(self, local_name, parent_module_globals, name):
不一定一致的，local_name起到as的作用

2024-09-06 02:20 UTC, drcege commented on data_juicer/utils/lazy_loader.py
> +    def __init__(self, local_name, parent_module_globals, name):
事实上，返回值已经充当了 as 的作用，比如
```python
pd1 = LazyLoader('pd2', globals(), 'pandas')
pd2.DataFrame is pd1.DataFrame  # True
```
pd1 和 pd2 都是 pandas 的别名，两处设置冗余且容易混淆：LazyLoader 中 local_name 在前面，而 import pandas as pd 的别名在后面，容易搞错顺序。
理想情况下，`pd = LazyLoader('pandas')` 是最简洁易用的方案。

2024-09-06 02:27 UTC, BeachWang commented on data_juicer/utils/lazy_loader.py
> +    def __init__(self, local_name, parent_module_globals, name):
这个没办法自动获取吧，globals()返回跟调用所在的文件有关。

2024-09-06 02:41 UTC, drcege commented on data_juicer/utils/model_utils.py
> +            MODEL_ZOO[model_key].to('cpu')
直接删除引用开销更低，应该也能起到相同的效果
```python
del MODEL_ZOO[model_key]
```

2024-09-06 02:41 UTC, drcege commented on data_juicer/utils/lazy_loader.py
> +    def __init__(self, local_name, parent_module_globals, name):
我测试可以的：
```python
# 获取调用堆栈当前帧的上一帧
frame = inspect.currentframe().f_back
# 获取调用者的模块的 globals
caller_globals = frame.f_globals
# 使用自动获取值
self._parent_module_globals = caller_globals
```

2024-09-09 03:39 UTC, BeachWang commented on data_juicer/utils/model_utils.py
> +            MODEL_ZOO[model_key].to('cpu')
这个试过了，不行的

2024-09-09 06:10 UTC, BeachWang commented on data_juicer/utils/lazy_loader.py
> +    def __init__(self, local_name, parent_module_globals, name):
直接使用lazy_loader.load

2024-09-09 06:10 UTC, BeachWang commented on data_juicer/utils/lazy_loader.py
> +    def __init__(self, local_name, parent_module_globals, name):
直接使用lazy_loader.load

2024-09-10 03:49 UTC, drcege requested changes

2024-09-10 03:49 UTC, drcege commented on data_juicer/utils/auto_install_utils.py
> +                subprocess.check_call(['pip', 'install', pkg])
最好也用 `sys.executable` 不然 pip 可能调用错误

2024-09-10 03:49 UTC, drcege commented on data_juicer/utils/availability_utils.py
> +    package_exists = _is_package_installed(pkg_name)
这里判断的是导入包的名字，而不是安装包的名字

2024-09-10 03:49 UTC, drcege commented on data_juicer/utils/availability_utils.py
如果改为 `AutoInstaller`, `AvailabilityChecking` 和 `UnavailableOperator` 就没有作用了，那么整个 `availability_utils.py` 文件就可以删掉；对应地，`ops/load.py` 中关于 `UNAVAILABLE_OPERATORS` 的判断逻辑也要调整

@HYLcool @yxdyc  也再仔细审阅下是否合适

2024-09-10 03:52 UTC, drcege commented on data_juicer/utils/availability_utils.py
如果有些激进或者还需商榷，可以拆分为 lazy_loader 和 autoinstall 两个 PR

2024-09-14 01:52 UTC, BeachWang commented on data_juicer/utils/availability_utils.py
> +    package_exists = _is_package_installed(pkg_name)
但是看代码之前availability往里传的参数写的是安装包的名字。

2024-09-14 01:57 UTC, drcege commented on data_juicer/utils/availability_utils.py
> +    package_exists = _is_package_installed(pkg_name)
这里跟 AvailabilityChecking 没有关系，是一个独立的函数，快速判断某个包是否可导入

2024-09-23 11:06 UTC, BeachWang commented on data_juicer/utils/availability_utils.py
经讨论，AutoInstaller可以方便之后构建按照算子安装环境的tool，建议合并

2024-09-25 06:14 UTC, drcege approved these changes

2024-09-25 06:18 UTC, merged